spring.application.name=skyreserve-notification
server.port=8081

# Kafka Ayarlari
spring.kafka.bootstrap-servers=localhost:9092

# Mesajlar? okuyacak format? zorla belirtelim (Hata pay?n? siler)
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Bu grubun adi önemli, mesajin kime gidecegini belirler
spring.kafka.consumer.group-id=notification-group

# Mesajlari en bastan mi yoksa yeni gelenleri mi okusun?
spring.kafka.consumer.auto-offset-reset=earliest